# NumPy Array Creation
This notebook demonstrates different ways to create arrays using NumPy.

In [2]:
import numpy as np

## Create array from Python list

In [3]:
arr1 = np.array([1, 2, 3, 4, 5])
arr1

array([1, 2, 3, 4, 5])

## Create 2D array

In [4]:
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

## Zeros array

In [5]:
zeros_arr = np.zeros((3, 4)) # 3 column and 4 row
zeros_arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

## Ones array

In [6]:
ones_arr = np.ones((2, 3))
ones_arr

array([[1., 1., 1.],
       [1., 1., 1.]])

## Range array

In [7]:
range_arr = np.arange(1, 10, 2) #start step stop

range_arr

array([1, 3, 5, 7, 9])

## Linspace array

In [8]:
linspace_arr = np.linspace(0, 1, 5)
linspace_arr

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

## Identity matrix

In [9]:
identity_arr = np.eye(4)
identity_arr

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Random array

In [10]:
random_arr = np.random.rand(3, 3)  #arrange with random values of 0 to 1
random_arr

array([[0.59487461, 0.58072014, 0.10563318],
       [0.40037527, 0.40073019, 0.5015866 ],
       [0.21509743, 0.10214653, 0.19025144]])

## Array properties

In [11]:
arr1.shape, arr1.dtype, arr1.ndim

((5,), dtype('int64'), 1)

In [14]:
np.random.rand(2,3) #uniform distribution (0 to 1 range)

array([[0.19407382, 0.22116715, 0.44008206],
       [0.52025247, 0.37173116, 0.03842692]])

In [16]:
np.random.randn(2,3)   # the values can be -ve or +ve

array([[-0.95433796,  2.18644351, -2.19174049],
       [-0.58315773, -1.04577259, -1.73262692]])

In [19]:
np.random.randint (1,10,(2,3))  #random number between 1-9

array([[4, 5, 1],
       [7, 3, 1]], dtype=int32)

In [28]:
m=[1,2,3,4,8]
np.zeros_like(m)


array([0, 0, 0, 0, 0])

In [29]:
np.ones_like(m)

array([1, 1, 1, 1, 1])