# NumPy Array Indexing
This notebook explains NumPy array indexing with examples.

In [1]:
import numpy as np

## 1D Array Indexing

In [4]:
arr = np.array([10, 20, 30, 40, 50])
# arr[0]
arr[2]
# arr[-1]

np.int64(30)

## 1D Array Slicing

In [5]:
arr[1:4]
arr[:3]
arr[2:]
arr[::2]

array([10, 30, 50])

## 2D Array Indexing

In [6]:
arr2d = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
arr2d[0, 0]
arr2d[1, 2]
arr2d[-1, -1]

np.int64(9)

## 2D Array Slicing

In [7]:
arr2d[0:2, 1:3]
arr2d[:, 1]
arr2d[1, :]

array([4, 5, 6])

## Boolean Indexing

In [8]:
arr = np.array([5, 10, 15, 20, 25])
arr[arr > 15]

array([20, 25])

## Fancy Indexing

In [9]:
arr = np.array([100, 200, 300, 400])
arr[[0, 2]]

array([100, 300])

## Modify Values Using Indexing

In [ ]:
arr = np.array([1, 2, 3, 4])
arr[1] = 20
arr

## Conditional Update

In [ ]:
arr = np.array([10, 20, 30, 40])
arr[arr % 20 == 0] = 0
arr