# NumPy Array Manipulation
This notebook covers common NumPy array manipulation techniques.

In [1]:
import numpy as np

## Reshape Array

In [2]:
arr = np.array([1, 2, 3, 4, 5, 6])
arr.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

## Flatten Array

In [3]:
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
arr2d.flatten()

array([1, 2, 3, 4, 5, 6])

## Transpose Array

In [4]:
arr2d.T

array([[1, 4],
       [2, 5],
       [3, 6]])

## Join Arrays (concatenate)

In [5]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6])

## Stack Arrays

In [8]:
np.vstack((a, b))
np.hstack((a, b))

array([1, 2, 3, 4, 5, 6])

## Split Arrays

In [19]:
arr = np.array([10, 20, 30, 40, 50, 60])
np.split(arr, 3)
# np.array_split(arr,5)


ValueError: vsplit only works on arrays of 2 or more dimensions

## Insert Elements

In [27]:


arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])

r=np.vsplit(arr, 3)
r=np.hsplit(arr, 3)
r


[array([[1],
        [4],
        [7]]),
 array([[2],
        [5],
        [8]]),
 array([[3],
        [6],
        [9]])]

In [10]:
np.insert(arr, 2, 99)

array([10, 20, 99, 30, 40, 50, 60])

## Delete Elements

In [18]:
np.delete(arr, 1)

array([10, 30, 40, 50, 60])

## Append Elements

In [17]:
np.append(arr, [70, 80])

array([10, 20, 30, 40, 50, 60, 70, 80])

## Sorting Arrays

In [16]:
unsorted = np.array([40, 10, 30, 20])
np.sort(unsorted)

array([10, 20, 30, 40])

## Unique Values

In [15]:
np.unique([1, 2, 2, 3, 3, 3])

array([1, 2, 3])